version: 2
jobs:
  build:
    environment:
      GOBIN: "/output"
    docker:
      - image: golang:1.8

    working_directory: /go/src/github.com/gtonic/nexus-cli

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: go get -v
          
      - store_artifacts:
          path: /output

      - run:
          name: Run Unit Tests
          command: go test
